### PR TITLE
Ilia fix new post not being center

### PR DESCRIPTION
**Pull request by iliaamiri**

### CODE REVIEW

**Comment by iliaamiri** [comment]
@Roncyboy Hey Terrence, just a reminder I was wondering if we could have this change on production? 👀

I really wanted to center that div 😂

Thanks man.

**Comment by Roncyboy** [comment]
> @Roncyboy Hey Terrence, just a reminder I was wondering if we could have this change on production? 👀
> 
> I really wanted to center that div 😂
> 
> Thanks man.

I believe I pushed this to production but I will accept PR and make sure it is working.

Sorry for the late reply.

**Review by Roncyboy — COMMENTED** [review]
LGTM

**Review by Roncyboy — COMMENTED** [review]
Default is now comment not Approve..

**Review by Roncyboy — APPROVED** [review]

**Comment by iliaamiri** [comment]
@Roncyboy Thank you so much Terrence.

No problem. It's all good 😄

**Pull request merged**
